{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "KartrocketAPI",
    "description": "All the api's you need are listed here.",
    "license": {
      "name": "MIT",
      "url": "http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT"
    }
  },
  "basePath": "/index.php?route=feed/feed/web_api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/category": {
      "get": {
        "tags": [
          "Category and Categories"
        ],
        "description": "Get Category",
        "operationId": "Get_Category",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "type": "integer",
            "description": "category id"
          }
        ],
        "responses": {
          "200": {
            "description": "Category details",
            "schema": {
              "$ref": "#/definitions/getCategoryResponse"
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "Category and Categories"
        ],
        "description": "Get Category",
        "operationId": "Get_Categories",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "level",
            "in": "query",
            "required": true,
            "type": "integer",
            "description": "Up to which level you want the API to traverse in category tree"
          },
          {
            "name": "parent",
            "in": "query",
            "required": true,
            "type": "integer",
            "description": "parent category"
          }
        ],
        "responses": {
          "200": {
            "description": "Category details",
            "schema": {
              "$ref": "#/definitions/categoriesResponse"
            }
          }
        }
      }
    },
    "/product": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "get specified product",
        "operationId": "get_product",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": true,
            "type": "integer",
            "description": "product id"
          },
          {
            "name": "sku",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Product SKU"
          }
        ],
        "responses": {
          "200": {
            "description": "Json formatted product details",
            "schema": {
              "$ref": "#/definitions/getProductResponse"
            }
          }
        }
      }
    },
    "/get_invoice": {
      "get": {
        "tags": [
          "Order"
        ],
        "description": "get pdf file of invoice",
        "operationId": "get_invoice",
        "produces": [
          "application/json"
        ],
        "parameters": [
          
          {
            "name": "order_id",
            "in": "query",
            "required": true,
            "type": "integer",
            "description": "order id"
          }
        ],
        "responses": {
          "200": {
            "description": "Pdf file"
          }
        }
      }
    },
    "/products": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "Get all products in specific category",
        "operationId": "getSpecificProducts",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "category",
            "in": "query",
            "required": true,
            "type": "integer",
            "description": "specific category id"
          }
        ],
        "responses": {
          "200": {
            "description": "Json formatted products in specified category",
            "schema": {
              "$ref": "#/definitions/getProductsResponse"
            }
          }
        }
      }
    },
    "/search_all_products": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "Search products",
        "operationId": "searchProduct",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "filter_name",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "name of the filter"
          }
        ],
        "responses": {
          "200": {
            "description": "Search results",
            "schema": {
              "$ref": "#/definitions/searchResponse"
            }
          }
        }
      }
    },
    "/addproduct": {
      "post": {
        "tags": [
          "Product"
        ],
        "description": "Add product",
        "operationId": "addProduct",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "description": "product data",
            "schema": {
              "$ref": "#/definitions/addProductRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product added",
            "schema": {
              "$ref": "#/definitions/addProductResponse"
            }
          }
        }
      }
    },
    "/cart/addMultiple": {
      "post": {
        "tags": [
          "Cart"
        ],
        "description": "add multiple cart items",
        "operationId": "addToCart",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "payload",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/addToCartRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "addToCartResponse",
            "schema": {
              "$ref": "#/definitions/addToCartResponse"
            }
          }
        }
      }
    },
    "/checkout/cart/apiViewCart": {
      "get": {
        "tags": [
          "Cart"
        ],
        "description": "View Cart",
        "operationId": "viewCart",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "List of items in cart",
            "schema": {
              "$ref": "#/definitions/viewCartResponse"
            }
          }
        }
      }
    },
    "/removeProAPI": {
      "post": {
        "tags": [
          "Cart"
        ],
        "description": "Remove product from cart",
        "operationId": "removeCartProduct",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "remproapi",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/remProApiRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Product removed",
            "schema": {
              "$ref": "#/definitions/remProApiResponse"
            }
          }
        }
      }
    },
    "/emptyCartAPI": {
      "get": {
        "tags": [
          "Cart"
        ],
        "description": "Empty cart request",
        "operationId": "emptyCart",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Empty Cart Response",
            "schema": {
              "$ref": "#/definitions/emptyCartResponse"
            }
          }
        }
      }
    },
    "/stock": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "Update stoke",
        "operationId": "updateProductStoke",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sku",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "sku of product'"
          },
          {
            "name": "qty",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "quantity of product"
          },
          {
            "name": "price",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "price of product"
          }
        ],
        "responses": {
          "200": {
            "description": "Update stoke response",
            "schema": {
              "$ref": "#/definitions/updateStokeResponse"
            }
          }
        }
      }
    },
    "/optionstock": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "Update Uption stock",
        "operationId": "updateStock",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sku",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "sku of product"
          },
          {
            "name": "option_sku",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "sku of product option"
          },
          {
            "name": "qty",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "product option quantity"
          },
          {
            "name": "price",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "product option price"
          },
          {
            "name": "weight",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "product option weight"
          }
        ],
        "responses": {
          "200": {
            "description": "json response of result",
            "schema": {
              "$ref": "#/definitions/updateStockResponse"
            }
          }
        }
      }
    },
    "/convert_currency": {
      "post": {
        "tags": [
          "Currency"
        ],
        "description": "Convert Currency",
        "operationId": "convertCurrency",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/convertCurrencyRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Convert Currency response",
            "schema": {
              "$ref": "#/definitions/convertCurrencyResponse"
            }
          }
        }
      }
    },
    "/list_currency": {
      "get": {
        "tags": [
          "Currency"
        ],
        "description": "List Currency",
        "operationId": "listCurrency",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Response of list_currency",
            "schema": {
              "$ref": "#/definitions/listCurrencyResponse"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Login"
        ],
        "description": "Login to store",
        "operationId": "login",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "route",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/loginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login Success",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "tags": [
          "Register"
        ],
        "description": "Register Request",
        "operationId": "register",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/registerRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Register Success",
            "schema": {
              "$ref": "#/definitions/registerResponse"
            }
          }
        }
      }
    },
    "/best_sellers": {
      "get": {
        "tags": [
          "Best Seller"
        ],
        "description": "Best Seller Product",
        "operationId": "bestSellerProduct",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "best Seller Response",
            "schema": {
              "$ref": "#/definitions/bestSellerResponse"
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "tags": [
          "Order"
        ],
        "description": "Get Orders",
        "operationId": "getOrder",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "order_id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "Order id"
          }
        ],
        "responses": {
          "200": {
            "description": "Response in json format",
            "schema": {
              "$ref": "#/definitions/getOrderResponse"
            }
          }
        }
      }
    },
    "/addorder": {
      "post": {
        "tags": [
          "Order"
        ],
        "description": "Add new order",
        "operationId": "addorder",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/addOrderRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order added Successfully",
            "schema": {
              "$ref": "#/definitions/addOrderResponse"
            }
          }
        }
      }
    },
    "/coupons": {
      "get": {
        "tags": [
          "Coupon"
        ],
        "description": "Get coupons",
        "operationId": "coupons",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "code",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "coupon code"
          },
          {
            "name": "date_from",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "from which date"
          },
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "page number"
          },
          {
            "name": "date_to",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "to which date in unix dateTime format"
          }
        ],
        "responses": {
          "200": {
            "description": "Json response of request",
            "schema": {
              "$ref": "#/definitions/couponResponse"
            }
          }
        }
      }
    },
    "/ordercount": {
      "get": {
        "tags": [
          "Order"
        ],
        "description": "COunt orders",
        "operationId": "orderCount",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Json response",
            "schema": {
              "$ref": "#/definitions/orderCountResponse"
            }
          }
        }
      }
    },
    "/productcount": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "Get count of products",
        "operationId": "productCount",
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Json response of count",
            "schema": {
              "$ref": "#/definitions/productCountResponse"
            }
          }
        }
      }
    },
    "/addchannelproduct": {
      "post": {
        "tags": [
          "Channel Products"
        ],
        "description": "add channel product",
        "operationId": "addChannelProductRequest",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "description": "data of product in json format",
            "schema": {
              "$ref": "#/definitions/addChannelProductRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Json response",
            "schema": {
              "$ref": "#/definitions/addChannelProductResponse"
            }
          }
        }
      }
    },
    "/channelproducts": {
      "get": {
        "tags": [
          "Product"
        ],
        "description": "get channel product",
        "operationId": "channelproducts",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "channel_id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "channe id"
          },
          {
            "name": "kartrocket_product_id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "kartrocket product id"
          },
          {
            "name": "channel_product_sku",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "sku of product in channel"
          },
          {
            "name": "page",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "page number"
          }
        ],
        "responses": {
          "200": {
            "description": "json encoded response",
            "schema": {
              "$ref": "#/definitions/getChannelProductResponse"
            }
          }
        }
      }
    },
    "/updateorders": {
      "get": {
        "tags": [
          "Order"
        ],
        "description": "Update order",
        "operationId": "updateOrder",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "order_id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "order id"
          },
          {
            "name": "order_status_id",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "order status id"
          },
          {
            "name": "courier_company",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "Name of courier company"
          },
          {
            "name": "awb_number",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "AWB number of order"
          }
        ],
        "responses": {
          "200": {
            "description": "Order updated Successfully",
            "schema": {
              "$ref": "#/definitions/updateOrderResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "getCategoryResponse": {
      "title": "Get Category",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "category": {
          "type": "object",
          "example": {
            "id": 1,
            "name": "Accessories",
            "description": "",
            "href": "http://saahil.kartrocket.co/index.php?route=product/category&category_id=1"
          }
        }
      },
      "required": [
        "success",
        "category"
      ]
    },
    "categoriesResponse": {
      "title": "Get Categories",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "category": {
          "type": "object",
          "example": {
            "id": 1,
            "name": "Accessories",
            "description": "",
            "href": "http://saahil.kartrocket.co/index.php?route=product/category&category_id=1"
          }
        }
      },
      "required": [
        "success",
        "category"
      ]
    },
    "getProductResponse": {
      "title": "Get Products",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "category": {
          "type": "object",
          "example": {
            "id": 1,
            "name": "Accessories",
            "description": "",
            "href": "http://saahil.kartrocket.co/index.php?route=product/category&category_id=1"
          }
        }
      },
      "required": [
        "success",
        "category"
      ]
    },
    "getProductsResponse": {
      "title": "Get Products",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "category": {
          "type": "object",
          "example": {
            "id": 1,
            "name": "Accessories",
            "description": "",
            "href": "http://saahil.kartrocket.co/index.php?route=product/category&category_id=1"
          }
        }
      },
      "required": [
        "success",
        "category"
      ]
    },
    "searchResponse": {
      "title": "Get Products",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "category": {
          "type": "object",
          "example": {
            "id": 1,
            "name": "Accessories",
            "description": "",
            "href": "http://saahil.kartrocket.co/index.php?route=product/category&category_id=1"
          }
        }
      },
      "required": [
        "success",
        "category"
      ]
    },
    "addProductRequest": {
      "title": "Get Products",
      "type": "object",
      "properties": {
        "data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Product Name",
              "example": "Jeans"
            },
            "description": {
              "type": "string",
              "description": "Product description",
              "example": "New Design Jeans"
            },
            "meta_title": {
              "type": "string",
              "description": "Product Meta Title"
            },
            "meta_description": {
              "type": "string",
              "description": "Product Meta Description"
            },
            "meta_keyword": {
              "type": "string",
              "description": "Product meta keyword"
            },
            "manufacturer": {
              "type": "string",
              "description": "manufacturer"
            },
            "sku": {
              "type": "string",
              "description": "Unique SKU of product",
              "example": "SKU1"
            },
            "model": {
              "type": "string",
              "description": "Product model",
              "example": "X1"
            },
            "price": {
              "type": "integer",
              "description": "Product Price in INR",
              "example": "1000"
            },
            "quantity": {
              "type": "integer",
              "description": "Product quantity",
              "example": "10"
            },
            "shipping": {
              "type": "string",
              "description": "provided or not (0/1)",
              "example": "1"
            },
            "subtract": {
              "type": "string",
              "description": "Subtract or not (0/1)",
              "example": "1"
            },
            "image": {
              "type": "string",
              "description": "image path",
              "example": "data/product_main_image.jpg"
            },
            "status": {
              "type": "string",
              "description": "available or not (0/1)",
              "example": "1"
            },
            "keyword": {
              "type": "string",
              "description": "Product Name",
              "example": ""
            },
            "upc": {
              "type": "string",
              "description": "UPC",
              "example": "893789939"
            },
            "asin": {
              "type": "string",
              "description": "ASIN",
              "example": "DFJ788H8D8H"
            },
            "isbn": {
              "type": "string",
              "description": "ISBN",
              "example": "33289793"
            },
            "ean": {
              "type": "string",
              "description": "EAN",
              "example": "8612368"
            },
            "weight": {
              "type": "string",
              "description": "Product weight",
              "example": "2"
            },
            "length": {
              "type": "string",
              "description": "Product Length",
              "example": "10"
            },
            "width": {
              "type": "string",
              "description": "Product width",
              "example": "20"
            },
            "height": {
              "type": "string",
              "description": "Product height",
              "example": "5"
            },
            "tax_class_id": {
              "type": "string",
              "description": "tax class id",
              "example": "9"
            },
            "download_images": {
              "type": "string",
              "description": "download images (0/1)",
              "example": "1"
            },
            "product_image": {
              "type": "array",
              "description": "Product image paths",
              "items": {
                "type": "string"
                },
              "example": [
                "data/product_image_1.jpg",
                "data/product_image_2.jpg",
                "data/product_image_3.jpg",
                "data/product_image_n.jpg"
              ]
            },
            "product_option": {
              "type": "object",
              "description": "Product Options",
              "example": {
                "Option One": [
                  {
                    "option_name": "Option 1 value 1",
                    "quantity": "10",
                    "option_sku": "OOV1",
                    "weight": "0.4",
                    "subtract": "1"
                  },
                  {
                    "option_name": "Option 1 value 2",
                    "quantity": "5",
                    "option_sku": "OOV2",
                    "weight": "1.2",
                    "subtract": "0"
                  }
                ],
                "Option Two": [
                  {
                    "option_name": "Option 2 value 1",
                    "quantity": "10",
                    "option_sku": "OTV1",
                    "weight": "0.4",
                    "subtract": "1"
                  },
                  {
                    "option_name": "Option 2 value 2",
                    "quantity": "5",
                    "option_sku": "OV2",
                    "weight": "1.2",
                    "subtract": "1"
                  }
                ]
              }
            },
            "product_attribute": {
              "type": "array",
              "description": "Product attributes",
              "items": {
                "type": "string"
                },
              "example": [
                {
                  "group": "Attribute Group 1",
                  "name": "Attribute 1",
                  "description": "Attribute Value 1"
                },
                {
                  "group": "Attribute Group 2",
                  "name": "Attribute 2",
                  "description": "Attribute Value 2"
                }
              ]
            },
            "product_category": {
              "type": "array",
              "description": "Product category",
              "items": {
                "type": "string"
              },
              "example": [
                "Category One>Category Two",
                "Category One>Category Three",
                "Category Four"
              ]
            }
          }
        }
      },
      "required": [
        "data"
      ]
    },
    "addProductResponse": {
      "title": "Add Product response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": "true"
        },
        "product_added": {
          "type": "string",
          "example": "151"
        }
      },
      "required": [
        "success",
        "product_added"
      ]
    },
    "addToCartRequest": {
      "title": "Addnto cart",
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "properties": {
            "products": {
              "type": "array",
              "items": {
                "type": "string"
                },
              "example": [
                {
                  "product_id": 1,
                  "quantity": 1
                }
              ]
            }
          }
        }
      },
      "required": [
        "payload"
      ]
    },
    "addToCartResponse": {
      "title": "addToCartRequest",
      "type": "object",
      "properties": {
        "success": {
          "type": "string",
          "example": "Success: You have added Product 1</a> to your shopping cart</a>!"
        },
        "total": {
          "type": "string",
          "example": "1 item(s) - Rs.10"
        }
      },
      "required": [
        "success",
        "total"
      ]
    },
    "viewCartResponse": {
      "title": "View Cart details",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": "true"
        },
        "products": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            {
              "product_id": 1,
              "key": 1,
              "thumb": "http://res.cloudinary.com/kartrocket/image/fetch/w_250,q_80,h_150,c_pad,b_white,f_auto,fl_progressive/http%3A%2F%2Fkartrocket-mtp.s3.amazonaws.com%2Fall-     stores%2Fimage_anchal%2Fdata%2Flogo%2F11474109494709-Aurelia-Yellow-Woven-Design-Kurta-3291474109494344-1.jpg",
              "name": "Product 1",
              "model": "P1",
              "sku": "GY893D832",
              "option": [],
              "quantity": "1",
              "stock": "true",
              "price": "1000",
              "total": "1000"
            }
          ]
        },
        "totals": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            {
              "code": "sub_total",
              "title": "Sub-Total",
              "text": "Rs.10",
              "value": 10,
              "sort_order": "1"
            },
            {
              "code": "sub_total",
              "title": "Sub-Total",
              "text": "Rs.10",
              "value": 10,
              "sort_order": "1"
            }
          ]
        }
      },
      "required": [
        "success",
        "products",
        "totals"
      ]
    },
    "remProApiRequest": {
      "title": "rem Product Request",
      "type": "object",
      "properties": {
        "remproapi": {
          "type": "object",
          "properties": {
            "product": {
              "type": "string",
              "example": "1"
            }
          }
        }
      }
    },
    "remProApiResponse": {
      "title": "rem Product Response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": {
            "success": "true"
          }
        },
        "msg": {
          "type": "string",
          "example": "Removed Successfully"
        }
      }
    },
    "emptyCartResponse": {
      "title": "Empty Cart Response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": {
            "success": "true"
          }
        },
        "msg": {
          "type": "string",
          "example": "Cart Empty"
        }
      }
    },
    "updateStokeResponse": {
      "title": "Empty Cart Response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": {
            "success": "true"
          }
        },
        "msg": {
          "type": "string",
          "example": "Product with mentioned SKU updated"
        }
      }
    },
    "bestSellerResponse": {
      "title": "Best Seller Response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": {
            "success": "true"
          }
        },
        "bestseller": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            {
              "product_id": "8",
              "model": "P8",
              "SKU": "P8",
              "name": "Product 8",
              "thumb": "http://res.cloudinary.com/kartrocket/image/fetch/w_300,q_80,h_500,c_pad,b_white,f_auto,fl_progressive/http%3A%2F%2Fkartrocket- mtp.s3.amazonaws.com%2Fall-stores%2Fimage_anchal%2Fdata%2Fnew8.jpg",
              "zoom_thumb": "http://kartrocket-mtp.s3.amazonaws.com/all-stores/image_anchal/data/new8.jpg",
              "description": "This is a Test Product..",
              "price": "Rs.1,000",
              "special": "Rs.750",
              "tax": false,
              "quantity": "0",
              "status": "1"
            }
          ]
        }
      }
    },
    "loginRequest": {
      "title": "Login Request",
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "example": "abcd@xyz.com"
        },
        "password": {
          "type": "string",
          "example": "doDOJk332"
        }
      }
    },
    "loginResponse": {
      "title": "Login Response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": "true"
        },
        "customer": {
          "type": "object",
          "properties": {
            "customer_id": {
              "type": "string",
              "example": "60"
            },
            "firstname": {
              "type": "string",
              "example": "John"
            },
            "lastname": {
              "type": "string",
              "example": "Doe"
            },
            "email": {
              "type": "string",
              "example": "abcd@gmail.com"
            },
            "telephone": {
              "type": "string",
              "example": "1234567890"
            },
            "mobile": {
              "type": "string",
              "example": "0987654321"
            },
            "status": {
              "type": "string",
              "example": "1"
            },
            "date_added": {
              "type": "string",
              "example": "2016-11-16 07:12:14"
            },
            "date_last_action": {
              "type": "string",
              "example": "2016-11-16 07:12:14"
            }
          }
        }
      }
    },
    "registerRequest": {
      "title": "Register Request",
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "firstname": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password",
        "firstname"
      ]
    },
    "registerResponse": {
      "title": "Register response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": true
        },
        "customer": {
          "type": "string",
          "example": "60"
        }
      }
    },
    "listCurrencyResponse": {
      "title": "List Currency response",
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean",
          "example": true
        },
        "data": {
          "type": "object",
          "properties": {
            "GBP": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string",
                  "example": "GBP"
                },
                "title": {
                  "type": "string",
                  "example": "Pound Sterling"
                },
                "symbol_left": {
                  "type": "string",
                  "example": "Â£"
                },
                "symbol_right": {
                  "type": "string",
                  "example": "@"
                },
                "value": {
                  "type": "string",
                  "example": "0.01190000"
                }
              }
            },
            "USD": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string",
                  "example": "USD"
                },
                "title": {
                  "type": "string",
                  "example": "US Dollar"
                },
                "symbol_left": {
                  "type": "string",
                  "example": "$"
                },
                "symbol_right": {
                  "type": "string",
                  "example": "@"
                },
                "value": {
                  "type": "string",
                  "example": "0.01470000"
                }
              }
            },
            "INR": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string",
                  "example": "INR"
                },
                "title": {
                  "type": "string",
                  "example": "Indian Rupee"
                },
                "symbol_left": {
                  "type": "string",
                  "example": "Rs."
                },
                "symbol_right": {
                  "type": "string",
                  "example": ""
                },
                "value": {
                  "type": "string",
                  "example": "1.000000"
                }
              }
            }
          }
        }
      }
    },
      "convertCurrencyRequest": {
        "title": "Convert Currency request",
        "type": "object",
        "properties": {
          "price": {
            "type": "string",
            "example": "43"
          },
          "from": {
            "type": "string",
            "example": "USD"
          },
          "to": {
            "type": "string",
            "example": "USD"
          }
        }
      },
      "convertCurrencyResponse": {
        "title": "Convert Currency response",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "price": {
            "type": "string",
            "example": "134.893781312"
          }
        }
      },
      "updateStockResponse": {
        "title": "Update product option stock",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "addOrderRequest": {
        "title": "add order request",
        "type": "object",
        "properties": {
          "import_order_id": {
            "type": "string"
          },
          "channel_id": {
            "type": "string"
          },
          "firstname": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "company": {
            "type": "string"
          },
          "address_1": {
            "type": "string"
          },
          "address_2": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "postcode": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "country_code": {
            "type": "string"
          },
          "telephone": {
            "type": "string"
          },
          "mobile": {
            "type": "string"
          },
          "fax": {
            "type": "string"
          },
          "payment_method": {
            "type": "string"
          },
          "payment_code": {
            "type": "string"
          },
          "shipping_method": {
            "type": "string"
          },
          "shipping_code": {
            "type": "string"
          },
          "order_status_id": {
            "type": "string"
          },
          "products": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              {
                "name": "Apple iPhone 4Sx",
                "model": "MB0010",
                "sku": "MB0010",
                "quantity": 1,
                "subtract": 1,
                "price": 145,
                "total": 145,
                "tax": 6.9047619047619,
                "reward": 0
              },
              {
                "name": "Apple iPhone 4C",
                "model": "MB0011",
                "sku": "MB0011",
                "quantity": 1,
                "subtract": 1,
                "price": 149,
                "total": 149,
                "tax": 6.9047619047619,
                "reward": 0
              }
            ]
          },
          "totals": {
            "type": "object",
            "properties": {
              "handling": {
                "type": "integer"
              },
              "low_order_fee": {
                "type": "integer"
              },
              "sub_total": {
                "type": "integer"
              },
              "tax": {
                "type": "integer"
              },
              "total": {
                "type": "integer"
              }
            }
          },
          "weight": {
            "type": "integer"
          },
          "weight_unit": {
            "type": "integer"
          },
          "comment": {
            "type": "integer"
          },
          "total": {
            "type": "integer"
          }
        }
      },
      "addOrderResponse": {
        "title": "Order added Successfully",
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "order_added": {
            "type": "object",
            "properties": {
              "status": {
                "type": "string"
              },
              "order_id": {
                "type": "integer"
              }
            }
          }
        }
      },
      "getOrderResponse": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "couponResponse": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "orderCountResponse": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "productCountResponse": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "addChannelProductRequest": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "addChannelProductResponse": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "getChannelProductResponse": {
        "title": "Order fetched succesfully",
        "type": "object"
      },
      "updateOrderResponse": {
        "title": "Json response of update Orders",
        "type": "object"
      }
    }
  }